language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
after_success:
  - npm run release
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
