language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
script:
- ./scripts/travis/script.sh
after_success:
- ./scripts/travis/after-success.sh
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
sudo: required
services:
- docker
