language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm test
after_success:
  - './docker/docker-push.sh chrome && ./docker/docker-push.sh firefox'
  - npm run release
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
sudo: required
services:
  - docker
