dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
before_install:
- 'npm prune'
before_script:
- 'git fetch --unshallow'
- '"$(npm bin)"/commitlint --from="$TRAVIS_BRANCH" --to="$TRAVIS_COMMIT"'
- '"$(npm bin)"/commitlint --from="$TRAVIS_COMMIT"'
script:
- 'npm test'
after_success:
- '< coverage/lcov.info "$(npm bin)"/coveralls'
