language: node_js
cache:
  directories:
  - node_modules
node_js:
- '7'
before_script:
- npm prune
script:
- ./scripts/travis/script.sh
after_success:
- ./scripts/travis/coveralls.sh
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
sudo: required
services:
- docker
