language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
before_script:
- ./node_modules/.bin/greenkeeper-lockfile-update
script:
- ./scripts/ci.sh
after_script:
- ./node_modules/.bin/greenkeeper-lockfile-upload
after_success:
- ./scripts/coveralls.sh
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
sudo: required
services:
- docker
