version: '2'

services:
  chrome:
    image: clebert/cybernaut-chrome:latest
    environment:
    - DEBUG=cybernaut:*
    volumes:
    - ./examples/dist:/opt/cybernaut-tests
    - ./tests:/opt/cybernaut-tests
    - /dev/shm:/dev/shm
  firefox:
    image: clebert/cybernaut-firefox:latest
    environment:
    - DEBUG=cybernaut:*
    volumes_from:
    - chrome
