FROM clebert/cybernaut-chrome

COPY config.json /opt/config.json

# The following file is copied into the Docker build context
# by the script `example/docker-build.sh`
COPY example.e2e.js /opt/e2e-test/example.e2e.js
